### ISSUE TITLE
not working on windows?

### ISSUE THREAD

**Issue by luoqpolyvi** [75lb/yuidoc2md#5]
I'm running on Windows 8

I got a js source dir which was built by yuidoc, now I'd like to turn docs to md.

This is my error

```
D:\dev\> yuidoc2md D:\Dev\js\lib\* > doc.md
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error:
Error: ENOENT, no such file or directory 'D:\Dev\js\lib\*'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at C:\Users\Qi\AppData\Roaming\npm\node_modules\yuidoc2md\lib\yuidoc2md.js:39:43
    at Array.forEach (native)
    at getTempDir (C:\Users\Qi\AppData\Roaming\npm\node_modules\yuidoc2md\lib\yuidoc2md.js:37:11)
    at Object.exports.getJson (C:\Users\Qi\AppData\Roaming\npm\node_modules\yuidoc2md\lib\yuidoc2md.js:64:18)
    at Object.exports.getMarkdown (C:\Users\Qi\AppData\Roaming\npm\node_modules\yuidoc2md\lib\yuidoc2md.js:54:24)
    at Object.<anonymous> (C:\Users\Qi\AppData\Roaming\npm\node_modules\yuidoc2md\cli.js:39:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by 75lb** [comment]
hi, thanks for the report.. i will add `*` wildcard support on Windows ASAP.. in the meantime, please specify each file separately i.e.: 

```
$ yuidoc2md file1.js  file2.js > docs.md
```

**Comment by luoqpolyvi** [comment]
file list working!
Expecting for fix, thanks

**Comment by luoqpolyvi** [comment]
btw, it didn't work on Mac either, got

```
EISDIR, illegal operation on a directory
```

**Comment by 75lb** [comment]
confirmed, will fix.. thanks again :)

**Comment by 75lb** [comment]
everything is fixed, i'm just waiting for the npm registry issues to get fixed so i can publish my changes (currently "npm publish" is broken).. will keep you posted..

**Comment by 75lb** [comment]
everything is published to npm now.. please run `npm update -g yuidoc2md` and close this issue if all is well.. cheers!

**Comment by luoqpolyvi** [comment]
Hi, just updated and tested, it worked only on first level dir. If there was any subdir, conversion got aborted with message `Input must be files only, these directories were ignored`.
Hopefully it would fully support

```
yuidoc2md src/* > doc.md   # even if any subdir under src
yuidoc2md lib/* ext/* src/* index.js > doc.md
```

Thanks

**Comment by 75lb** [comment]
Hi.. the `Input must be files only, these directories were ignored` message is just information, the process was not aborted.. I have tried to make the output messages more clear, please update (`npm update -g yuidoc2md`) and try again.. 

regarding subdirs, if you want to recurse use `**` instead of `*`.. so, your commands should look something like: 

```
yuidoc2md src/** > doc.md
yuidoc2md lib/** ext/** src/** index.js > doc.md
```

does that help?

**Comment by luoqpolyvi** [comment]
Well, everything's working now, thanks for quick fix

**Comment by 75lb** [comment]
good.. let me know if you have any other issues.
