### ISSUE TITLE
@private is ignored, causing private methods to show up in the output

### ISSUE THREAD

**Issue by IjzerenHein** [75lb/yuidoc2md#6]
Even though a method is marked as @private, it still shows up in the output.

**Comment by 75lb** [comment]
true.. 

quick question, would you consider a switch to the vastly superior [jsdoc](http://usejsdoc.org)? because i'm working on a [much improved markdown generator](https://github.com/75lb/jsdoc-to-markdown) (for an example, see everything from 'API Reference' down on [this project readme](https://github.com/75lb/handbrake-js).. also [here](https://github.com/75lb/wodge))

**Comment by IjzerenHein** [comment]
actually, I would.
That output looks nice, including all the examples. Also I'm still in the position of being able to switch, while there is not that much code.. Is there there grunt-plugin as well?
cheers

**Comment by 75lb** [comment]
Good. I will add a grunt plugin, later on. I will look into fixing your
yuidoc2md issues too, but jsdoc is my main focus.

**Comment by 75lb** [comment]
MapModifier rendered with https://github.com/75lb/jsdoc-to-markdown:
https://github.com/75lb/famous-map/blob/master/api/MapModifier.md

it's still a WIP, but any feedback welcome :+1:

**Comment by IjzerenHein** [comment]
Wauw, that looks great, love the index of functions!

The options aren't quite rendered okay, but I wanted to use an @enum for that anyway. Is @enum supported?

Also, the constructor sort of seems missing. How should I attribute the constructor, with or without the @method attribute?

Cheers, great work!

**Comment by 75lb** [comment]
yes, @enum is supported, but like everything else is in the early stages.. an example: https://github.com/75lb/file-set#filesetefiletype

glad you like the index, it's gives you a quick feel for the API surface.. 

will have a look into the options and constructor..

**Comment by 75lb** [comment]
is this looking any better? https://github.com/75lb/famous-map/blob/master/api/MapModifier.md

at the moment, as the module _is_ the MapModifier constructor function, the documentation for the constructor params is written in the @module doclet.. i will look into improving the generated documentation tomorrow to make it more obvious that the module is a constructor..

**Comment by 75lb** [comment]
btw, with jsdoc it's rarely necessary to use the @method or @function tag as the parser detects that you are documenting a function automatically

**Comment by IjzerenHein** [comment]
Love the way how it is displayed now!
Looking at it, it actually looks quite nice and logical combining the class & constructor. I was kinda used to having separate constructor/class, but javascript doesn't support that anyway. If you intend to support Java as well, then having a separate constructor/class would be more consistential.

The options and its child properties really look nice this way, wouldn't change a thing!

I'll upgrade the famous-map project to jsdoc-to-markdown, and do some additional testing.
Cheers!

**Comment by 75lb** [comment]
eek, an early-adopter! make sure you keep your `jsdoc2md` up to date then, as it's changing constantly.. but i will appreciate the extra testing - thanks!  just so you know, jsdoc has it own issues too which you should know about - here are the ones i have created in the last week: https://github.com/75lb/jsdoc-to-markdown/issues/3.. 

If have re-organised the documentation for MapModifier, moving the constructor docs from the @module back to the @class.. i think this is the best way to do it.. with this method, you can copy/paste the class and its docs to another file/module as one complete unit.. https://github.com/75lb/famous-map/blob/master/MapModifier.js

regarding the constructor and the module being the same thing, this is just how jsdoc does it.. here's a screenshot of the rendered jsdoc site for your class: 

![screen shot 2014-06-26 at 09 15 18](https://cloud.githubusercontent.com/assets/1247980/3396205/ca722600-fd0a-11e3-92c7-c11086180d60.png)

**Comment by 75lb** [comment]
this will be one of the most important jsdoc manual pages for you, having so many AMD modules: http://usejsdoc.org/howto-commonjs-modules.html

**Comment by 75lb** [comment]
two final things, before i need to do some "real" work (boring).. 
1. moved your author/copyright/license details from the file header to the @module.. 
2. added another npm script ("npm run readme") to the package.json which demonstrates how to embed generated docs in your readme.. see my readme for an example: https://github.com/75lb/famous-map

**Comment by IjzerenHein** [comment]
Hi, thanks for all the information.
I updated famous-map and used your suggestions, looks great!

While testing I found the following issues:
- @method is required, if I omit it (as you mentioned), no output is generated for that function
- @ignore is ignored

Using '@alias module:' and putting a name after @class, results in strange too much output at the end of file:
@class MapModifier
@alias module:MapModifier

Also I left @author, @license and @copyright in the header instead of the @module, because I don't want that information in the output.

Question: Is it possible to hide the scope-line: 'Scope: inner function of MapView' ?

I couldn't get @enum to work, because the enum is defined before the class-definition. I don't want to move the enum downwards because this will generate a lot of linting-errors.
See MapType enum: https://github.com/IjzerenHein/famous-map/blob/master/MapView.js

Also, love to see a grunt-task runner for jsdoc-to-markdown :)

Finally, I noticed that the params are not correctly displayed using some Markdown viewers. (Mou & http://jbt.github.io/markdown-editor) These viewers seem to require an additional CRLF after **Params**

Cheers, keep up the geat work!
And good luck with your job...

**Comment by 75lb** [comment]
great feedback, thanks.. 

grunt plugin: https://github.com/75lb/grunt-jsdoc-to-markdown

will look into your other points now..

**Comment by IjzerenHein** [comment]
Cool, thanks, I'll give it a go later!
Cheers!

**Comment by IjzerenHein** [comment]
I installed the grunt plugin, works great, thanks!

I did get an error while installing, but when I tried installing it with sudo the problem was gone.
If you want more details on this, let me know.

**Comment by 75lb** [comment]
sudo & perms issues are specific to your OS.. are you on a Mac? From OSX 10.8 onward, it's no longer necessary to run `npm install` commands with `sudo`.. it is always necessary on Linux, though

**Comment by IjzerenHein** [comment]
Yeah I'm on a Mac.
This is the error I got when running 'npm update jsdoc-to-markdown':

npm http GET https://registry.npmjs.org/jsdoc-to-markdown/latest
npm http 304 https://registry.npmjs.org/jsdoc-to-markdown/latest
npm http GET https://registry.npmjs.org/jsdoc-to-markdown
npm http 304 https://registry.npmjs.org/jsdoc-to-markdown
Sadikuz:famous-map hein$ npm update -g jsdoc-to-markdown
npm http GET https://registry.npmjs.org/jsdoc-to-markdown/latest
npm http 304 https://registry.npmjs.org/jsdoc-to-markdown/latest
npm http GET https://registry.npmjs.org/jsdoc-to-markdown
npm http 304 https://registry.npmjs.org/jsdoc-to-markdown
Sadikuz:famous-map hein$ npm install grunt-jsdoc-to-markdown
npm WARN package.json famous-map@0.0.6 No repository field.
npm http GET https://registry.npmjs.org/grunt-jsdoc-to-markdown
npm http 304 https://registry.npmjs.org/grunt-jsdoc-to-markdown
npm ERR! error rolling back Error: EACCES, unlink '/Users/hein/repos/famous/famous-map/node_modules/grunt-jsdoc-to-markdown/node_modules/.bin/jsdoc2md'
npm ERR! error rolling back  grunt-jsdoc-to-markdown@0.1.1 { [Error: EACCES, unlink '/Users/hein/repos/famous/famous-map/node_modules/grunt-jsdoc-to-markdown/node_modules/.bin/jsdoc2md']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/Users/hein/repos/famous/famous-map/node_modules/grunt-jsdoc-to-markdown/node_modules/.bin/jsdoc2md' }
npm ERR! Error: EACCES, unlink '/Users/hein/repos/famous/famous-map/node_modules/grunt-jsdoc-to-markdown/node_modules/.bin/jsdoc2md'
npm ERR!  { [Error: EACCES, unlink '/Users/hein/repos/famous/famous-map/node_modules/grunt-jsdoc-to-markdown/node_modules/.bin/jsdoc2md']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/hein/repos/famous/famous-map/node_modules/grunt-jsdoc-to-markdown/node_modules/.bin/jsdoc2md' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "grunt-jsdoc-to-markdown"
npm ERR! cwd /Users/hein/repos/famous/famous-map
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.25
npm ERR! path /Users/hein/repos/famous/famous-map/node_modules/grunt-jsdoc-to-markdown/node_modules/.bin/jsdoc2md
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/Users/hein/repos/famous/famous-map/node_modules/grunt-jsdoc-to-markdown/node_modules/.bin/jsdoc2md'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/hein/repos/famous/famous-map/npm-debug.log
npm ERR! not ok code 0

**Comment by IjzerenHein** [comment]
Installing it with sudo works fine, and this is the output:

Sadikuz:famous-map hein$ sudo npm install grunt-jsdoc-to-markdown
npm WARN package.json famous-map@0.0.6 No repository field.
npm http GET https://registry.npmjs.org/grunt-jsdoc-to-markdown
npm http 304 https://registry.npmjs.org/grunt-jsdoc-to-markdown
npm http GET https://registry.npmjs.org/jsdoc-to-markdown
npm http 304 https://registry.npmjs.org/jsdoc-to-markdown
npm http GET https://registry.npmjs.org/command-line-args
npm http GET https://registry.npmjs.org/file-set
npm http GET https://registry.npmjs.org/console-dope
npm http GET https://registry.npmjs.org/jsdoc
npm http GET https://registry.npmjs.org/more-fs
npm http GET https://registry.npmjs.org/array-tools
npm http GET https://registry.npmjs.org/object-tools
npm http GET https://registry.npmjs.org/boil-js
npm http 304 https://registry.npmjs.org/file-set
npm http 304 https://registry.npmjs.org/jsdoc
npm http 304 https://registry.npmjs.org/more-fs
npm http 304 https://registry.npmjs.org/console-dope
npm http 304 https://registry.npmjs.org/command-line-args
npm http 304 https://registry.npmjs.org/boil-js
npm http 304 https://registry.npmjs.org/object-tools
npm http 304 https://registry.npmjs.org/array-tools
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/typical
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/handlebars-ansi/0.0.2
npm http GET https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/string-tools
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/nature
npm http 304 https://registry.npmjs.org/typical
npm http 304 https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/config-master
npm http GET https://registry.npmjs.org/front-matter-extractor
npm http GET https://registry.npmjs.org/handlebars-comparison
npm http GET https://registry.npmjs.org/handlebars-array
npm http GET https://registry.npmjs.org/handlebars-fileset
npm http GET https://registry.npmjs.org/handlebars-fs
npm http GET https://registry.npmjs.org/home-path
npm http GET https://registry.npmjs.org/handlebars-path
npm http GET https://registry.npmjs.org/handlebars-string
npm http GET https://registry.npmjs.org/handlebars-io
npm http GET https://registry.npmjs.org/handlebars
npm http 304 https://registry.npmjs.org/string-tools
npm http 304 https://registry.npmjs.org/handlebars-ansi/0.0.2
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/handlebars-array
npm http 304 https://registry.npmjs.org/handlebars-comparison
npm http 304 https://registry.npmjs.org/config-master
npm http 304 https://registry.npmjs.org/nature
npm http 304 https://registry.npmjs.org/handlebars-fileset
npm http 304 https://registry.npmjs.org/handlebars-fs
npm http 304 https://registry.npmjs.org/front-matter-extractor
npm http 304 https://registry.npmjs.org/handlebars-path
npm http 304 https://registry.npmjs.org/handlebars
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/home-path
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/handlebars-string
npm http GET https://registry.npmjs.org/ansi-escape-sequences/0.0.1
npm http 304 https://registry.npmjs.org/handlebars-io
npm http 304 https://registry.npmjs.org/ansi-escape-sequences/0.0.1
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/js-yaml
npm http GET https://github.com/ariya/esprima/tarball/49a2eccb243f29bd653b11e9419241a9d726af7c
npm http GET https://github.com/hegemonic/taffydb/tarball/master
npm http GET https://registry.npmjs.org/catharsis
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/requizzle
npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/js2xmlparser
npm http GET https://registry.npmjs.org/wrench
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/requizzle
npm http 304 https://registry.npmjs.org/catharsis
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/js2xmlparser
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/wrench
npm http 304 https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/underscore.string
npm http 200 https://github.com/hegemonic/taffydb/tarball/master
npm http 200 https://github.com/ariya/esprima/tarball/49a2eccb243f29bd653b11e9419241a9d726af7c
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/underscore-contrib
npm http 304 https://registry.npmjs.org/underscore-contrib
grunt-jsdoc-to-markdown@0.1.1 node_modules/grunt-jsdoc-to-markdown
└── jsdoc-to-markdown@0.2.9 (console-dope@0.3.6, object-tools@1.0.3, array-tools@1.1.1, file-set@0.2.0, more-fs@0.4.1, command-line-args@0.4.0, boil-js@0.1.10, jsdoc@3.3.0-dev)

**Comment by 75lb** [comment]
you should never have permission issues in your own home directory (`/Users/hein`), rebuild the `node_modules` folder.. in your project folder run: 

``` sh
$ sudo rm -rvf node_modules
$ npm install 
```

afterward, you should have `jsdoc2md` 0.2.10 - another update i just released.

**Comment by IjzerenHein** [comment]
Thanks. Tried your suggestion but still didn't work. After npm install I got this error:

npm ERR! git fetch -a origin (git://github.com/jsdoc3/jsdoc) error: cannot open FETCH_HEAD: Permission denied
npm ERR! notarget No compatible version found: jsdoc@'jsdoc3/jsdoc'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","3.2.0-dev","3.2.0","3.2.1","3.2.2","3.3.0-alpha1","3.3.0-alpha2","3.3.0-alpha3","3.3.0-alpha4","3.3.0-alpha5","3.3.0-alpha7","3.3.0-alpha8"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/hein/repos/famous/famous-map
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.25
npm ERR! code ETARGET

**Comment by 75lb** [comment]
interesting.. i just cloned `master` of famous-map and ran `npm install`, all the deps installed fine.. 

Your npm is rather old, could be time for a trip to http://nodejs.org.. or run `brew upgrade node`.. i'm running: 

``` sh
$ npm -v
1.4.16
$ node -v
v0.10.29
```

**Comment by IjzerenHein** [comment]
Alright I got it working.
Upgraded to latest node and npm as you suggested.
The newer npm produced better output, there was something wrong with the global jsdoc3 npm data.
It's now working fine, Thanks a lot Lloyd!
